version: "2.1"
services:
  grav:
    image: lscr.io/linuxserver/grav
    container_name: grav
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - ./gravcms:/config
    ports:
      - 8881:80
    restart: unless-stopped